apiVersion: v1
kind: Service
metadata:
  name: smart-hostel-app
  namespace: smart-hostel
spec:
  type: NodePort
  selector:
    app: smart-hostel-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080
