apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: smart-hostel
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpass
  MYSQL_USER: hostel
  MYSQL_PASSWORD: hostel_pass
  MYSQL_DATABASE: hostel_management
